      MODULE PibIntrType
        IMPLICIT NONE
!
! -------------------- NOTE: DO NOT EDIT THIS FILE. --------------------
! This file is generated.  Modifications will be lost!
! ----------------------------------------------------------------------
!
        INTEGER, PARAMETER :: ptik = kind(10000000)
        INTEGER, PARAMETER :: ptlk = selected_int_kind(16)
        INTEGER, PARAMETER :: ptrk = kind(1.0)
        INTEGER, PARAMETER :: ptdk = selected_real_kind(13,307)
!
      END MODULE PibIntrType
