#!/bin/python
""" SConscript for TPR library """

######################################################
#  SConscript file for TPR library
######################################################
import os
import fnmatch

Import('*')

######################################################
#  Retrieve list of files that need to be compiled
######################################################
srcs = []
for file in os.listdir(Dir('.').srcnode().abspath):
   if fnmatch.fnmatch(file, "*.f90"):
      srcs.append(file)


############################################
#  Customize the construction environment  #
############################################
#
if platform == 'cygwin':

   if fcompiler == 'lahey':
      env = Environment(options = opts)
      env.Append(ENV = {'PATH' : os.environ['PATH'], 'INCLUDE' : os.environ['INCLUDE'], 'LIB' : os.environ['LIB']})

      if buildType == 'debug':
         print ""
      elif buildType == 'release':
         print ""
      else:
         print ""

      print "Compiler " + fcompiler + " is currently unsupported on the " + platform + " platform"
      print ""
   elif fcompiler == 'ifort12' or fcompiler == 'ifort16' or fcompiler == 'ifort17':
      # Redefine construction environment in order to replace certain posix-specific construction
      # variables with values more appropriate for building on cygwin with Windows tool chain
      env = Environment(options = opts, platform = 'cygwin', tools=['default', 'f90', 'msvc', 'mslink', 'mslib', 'msvs'])

      for path in path_dict[fcompiler][target_arch] + path_dict[ccompiler][target_arch]:
         command = 'cygpath -u -p "' + path + '"' # transmute the path info from a Windows path to a cygwin path because
         cygwin_path = os.popen(command).read()   # cygwin python will expect to execute compilers using unix path conventions
         env.PrependENVPath('PATH', cygwin_path.rstrip('\n'))


      # Setup the INCLUDE environment variable so that compiler tools know where to go for header files
      for inc in include_dict[ccompiler][target_arch]:
         env.AppendENVPath('INCLUDE', inc, 'ENV', ";")

      # Setup the LIB environment variable so that the compiler tools know where to go for needed libraries
      for lib in lib_dict[fcompiler][target_arch] + lib_dict[ccompiler][target_arch]:
         env.AppendENVPath('LIB', lib, 'ENV', ";")

      env['PRINT_CMD_LINE_FUNC'] = build_utils.print_cmd_line
      env['CMD_LOGFILE'] = 'build-cmds.txt'

      env['OBJPREFIX'] = ''
      env['OBJSUFFIX'] = '.obj'
      env['RANLIBCOM'] = ''
      env['LIBPREFIX'] = ''
      env['LIBSUFFIX'] = '.lib'

      env['F90'] = 'ifort'
      env['F90COM'] = '$F90 $F90FLAGS $_F90INCFLAGS $_FORTRANMODFLAG /compile_only ${SOURCES.windows} /object:${TARGET.windows}'

      # Default Fortran compiler options
      env['F90FLAGS'] = ['/nologo',
                            ]

      env['FORTRANMODDIRPREFIX'] = '/module:'
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      # Now establish debug/release specific compiler flags and link options
      if buildType == 'debug':
         fortranFlags = ['/debug:full',                 # Enable full debug level information
                         '/check:bounds',               # Generate run-time message when array bounds are exceeded
                         '/check:format',               # Generate run-time message when FORMAT descriptor does not match the
                                                        # data type
                         '/check:pointer',              # Check for disassociated or uninitialized pointers
                                                        # or unallocated allocatable objects
                         '/check:uninit',               # Check for uninitialized variables
                         '/check:output_conversion',    # Generate run-time message when format truncation occurs
                         #'/check:arg_temp_created',
                         '/stand:f95',                  # Generate warning for non-stardard F95 coding
                         '/traceback',                  # Generate traceback information
                         '/warn:interfaces',            # Check interfaces of all subroutines and functions against an external set
                                                        # of interface blocks
                         '/warn:declarations',          # Issue an error message for any undeclared variables
                        # '/warn:unused',                # Enable warnings for a variable that is declared but never used
                         '/Qvc8',                       # Specifies compatibility with MSVS 2005
                         '/MT',                         # Tells linker to search for unresolved references in an optimized
                                                        # multithreaded, static run-time library (LIBCMT.LIB).  This is
                                                        # the same as /dbglibs, /threads, /libs:static
                         '/Qdiag-file:${SOURCES.base}.diag',  # write compiler diagnostics to a file
                         '/Qtrapuv',                    # Initialize local variables to a strange value
                         '/Qfp-stack-check',            # Check the stack for consistency
                         '/assume:minus0',              # Allow TRACE to calculate negative zero
                         '/fpe0',                       # Trap all floating point exceptions as errors (except underflows)
                         '/O1',                         # This option tells the compiler to enables optimizations for speed and
                                                        # disables some optimizations that increase code size and affect speed.
                         '/Ob2',                        # Enables inlining of any function at the compiler's discretion.
                         '/fp:source',
                        ]

      elif buildType == 'release':
         fortranFlags = ['/O2',
                         '/Qdiag-file:${SOURCES.base}.diag',  # write compiler diagnostics to a file
                         '/fp:source',
                        ]
      else:
        print "Not sure what type of build you want"
        print ""
        Exit(1)

      env.Append(F90FLAGS = fortranFlags)

   elif fcompiler == 'g95':
      env = Environment(options = opts, platform='cygwin', tools=['f90', 'default'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['F90'] = 'g95'
      env['F90FLAGS'] = '-fno-second-underscore'
      env['FORTRANMODDIRPREFIX'] = '-fmod='
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['-g']
      elif buildType == 'release':
         fortranFlags = ['-O']
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
      env.Append(F90FLAGS = fortranFlags)

   elif fcompiler == 'salford':
      env = Environment(options = opts)
      env.Append(ENV = {'PATH' : os.environ['PATH'], 'INCLUDE' : os.environ['INCLUDE'], 'LIB' : os.environ['LIB']})

      if buildType == 'debug':
         print ""
      elif buildType == 'release':
         print ""
      else:
         print ""

      print "Compiler " + fcompiler + " is currently unsupported on the " + platform + " platform"
      print ""
   else:
      print "Compiler " + fcompiler + " is currently unsupported on the " + platform + " platform"
      print ""


elif platform == 'win32':

   if fcompiler == 'cvf':
      env = Environment(options = opts, tools=['default', 'cvf', 'mslink', 'msvc', 'mslib', 'msvs'])
      env.Append(ENV = {'PATH' : os.environ['PATH'], 'INCLUDE' : os.environ['INCLUDE'], 'LIB' : os.environ['LIB']})

      if buildType == 'debug':
         print ""
      elif buildType == 'release':
         print ""
      else:
         print ""

      print "Compiler " + fcompiler + " is currently unsupported on the " + platform + " platform"
      print ""

   elif fcompiler == 'g95':
      env = Environment(options = opts)
      env.Append(ENV = {'PATH' : os.environ['PATH'], 'INCLUDE' : os.environ['INCLUDE'], 'LIB' : os.environ['LIB']})

      if buildType == 'debug':
         print ""
      elif buildType == 'release':
         print ""
      else:
         print ""

      print "Compiler " + fcompiler + " is currently unsupported on the " + platform + " platform"
      print ""

   else:
      print "Compiler " + fcompiler + " is currently unsupported on the " + platform + " platform"
      print ""


elif platform == 'linux' or platform == 'linux2':

   if fcompiler == 'lahey':
      env = Environment(options = opts, tools=['default', 'fortran'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['F90'] = 'lf95'
      env['F90FLAGS'] = '--nli'
      env['FORTRANMODDIRPREFIX'] = '--mod '
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['--trap',
                         '--trace',
                         '-g',
                         '--chk aesu'
                        ]
      elif buildType == 'release':
         fortranFlags = ['-O' ]
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
      env.Append(FORTRANFLAGS = fortranFlags)

      #  Special processing to deal with lahey compiler bug when compiling TPRFileAccessM.f90.  When
      #  debug mode is turned on, TPRFileAccessM.f90 takes a long time to compile, so compile it in
      #  optimized mode instead.
      if buildType == 'debug':
         env_special = env.Clone(F90FLAGS = '--nli -O')
         file = 'TPRFileAccessM.f90'
         obj = env_special.Object([file])
         srcs.remove(file)
         srcs.append(obj)

   elif fcompiler == 'pathscale':
      env = Environment(options = opts, tools=['f90', 'default'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['F90'] = 'pathf95'
      env['F90FLAGS'] = ['-m64', '-mcpu=opteron']
      env['FORTRANMODDIRPREFIX'] = '-module '
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['-C',
                         '-g'
                        ]
      elif buildType == 'release':
         fortranFlags = ['-O2']
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
      env.Append(F90FLAGS = fortranFlags)

   elif fcompiler == 'nag':
      env = Environment(options = opts, tools=['default', 'f90'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['F90'] = 'nagfor'
      env['F90FLAGS'] = ['-maxcontin=75',
                         '-kind=byte'
                        ]
      env['F90PATH'] = ["#" + tpr_build_dir]
      env['FORTRANMODDIRPREFIX'] = '-mdir '
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['-O0',
                         '-gline',
                         '-nan',
                         '-w=all',
                         '-g'
                        ]
      elif buildType == 'release':
         fortranFlags = ['-O0',
                         '-gline',
                         '-w=all',
                         '-g'
                        ]
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
      env.Append(F90FLAGS = fortranFlags)

   elif fcompiler == 'g95':
      env = Environment(options = opts, tools=['f90', 'default'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['F90'] = 'g95'
      env['F90FLAGS'] = '-fno-second-underscore'
      env['FORTRANMODDIRPREFIX'] = '-fmod='
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['-g']
      elif buildType == 'release':
         fortranFlags = ['-O']
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
      env.Append(F90FLAGS = fortranFlags)

   elif fcompiler == 'gfortran':
      env = Environment(options = opts, tools=['f90', 'default'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['F90'] = 'gfortran'
      env['F90FLAGS'] = '-fno-second-underscore'
      env['FORTRANMODDIRPREFIX'] = '-J'
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['-g']
      elif buildType == 'release':
         fortranFlags = ['-O']
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
      env.Append(F90FLAGS = fortranFlags)

   elif fcompiler == 'intel':
      env = Environment(options = opts, tools=['f90', 'default'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['F90'] = 'ifort'
      env['F90FLAGS'] = ['']
      env['FORTRANMODDIRPREFIX'] = ['-module ']
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['-g',
                         '-traceback',
                         '-check', 'all',
                         '-no-ftz',
                         '-fpe0',
                         ]
      elif buildType == 'release':
         fortranFlags = ['-O']
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
      env.Append(F90FLAGS = fortranFlags)

   else:
      print "Compiler " + fcompiler + " is currently unsupported on the " + platform + " platform"
      print ""
elif platform == 'darwin':
   if fcompiler == 'g95':
      env = Environment(options = opts, tools=['f90', 'default'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['F90'] = '/usr/local/bin/g95'
      env['F90FLAGS'] = '-fno-underscoring'
      env['FORTRANMODDIRPREFIX'] = '-fmod='
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['-g']
      elif buildType == 'release':
         fortranFlags = ['-msse3']
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90FLAGS = fortranFlags)

   elif fcompiler == 'intel':
      env = Environment(options = opts, tools=['f90', 'default'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['RANLIBFLAGS'] = ['-c']
      env['F90'] = 'ifort'
      env['F90FLAGS'] = ['']
      env['FORTRANMODDIRPREFIX'] = '-module '
      dir = env.Dir("#/" + tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['-g',
                         '-traceback',
                         '-check', 'all',
                         '-no-ftz',
                         '-fpe0',
                         ]
      elif buildType == 'release':
         fortranFlags = ['-O']
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
      env.Append(F90FLAGS = fortranFlags)
   elif fcompiler == 'gfortran':
      env = Environment(options = opts, tools=['f90', 'default'])
      env.Append(ENV = {'PATH' : os.environ['PATH']})
      env['CPPDEFINES'] = ['MACOSX']
      env['F90'] = 'gfortran'
      env['F90FLAGS'] = '-fno-underscoring'
      env['F90PATH'] = [trace_build_dir]
      env['FORTRANMODDIRPREFIX'] = '-J'
      dir = env.Dir(tpr_build_dir)
      env['FORTRANMODDIR'] = dir

      if buildType == 'debug':
         fortranFlags = ['-g']
      elif buildType == 'release':
         fortranFlags = ['-O']
      else:
         print "Unsupported buildType = " + buildType
         print ""
         Exit(1)

      env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
      env.Append(F90FLAGS = fortranFlags)
else:
   print ""

#  Print out the construction variables for debugging purposes if the user requests it
#if env['verbose'] == 1:
#   build_utils.DumpEnv(env)

# Make the build output prettier for all build environments

RPATH_var = '$_'+common_build_dir+os.sep+'libcommon.dylib'
env['__RPATH'] = RPATH_var
env['RPATHPREFIX'] = '-Wl,-rpath'
env['RPATHSUFFIX'] = ''
env['_RPATH'] = '${_concat(RPATHPREFIX, RPATH, RPATHSUFFIX, __env__)}'
#env = Environment(tools=['gcc','g++','gfortran','gnulink'])
#env.Tool('gnulink')
print RPATH_var
print "LINKCOM:%s"%env['LINKCOM']

open('dump.txt','w').write(env.Dump())
######################################################
#  Build the library
######################################################
if (projectType=='shared'):
    tpr_lib = env.SharedLibrary(target = 'TPRLib',
                                source = srcs
                                #LIBS = 'common',
                                #LIBPATH= common_build_dir,
                               )
else:
    tpr_lib = env.StaticLibrary(target = "TPRLib",
                            source = srcs
                           )


######################################################
# Build the Visual Studio Project file when under Windows
######################################################
#if env['PLATFORM'] == 'cygwin' or env['PLATFORM'] == 'win32':
#if env['PLATFORM'] == 'win32':
#   env.MSVSProject(target = 'TPRLib' + env['MSVSPROJECTSUFFIX'],
#                   srcs = srcs,
#                   buildtarget = tpr_lib,
#                   variant = 'Debug')
Return("tpr_lib")
