#!/bin/python
""" SConscript for common module library"""

######################################################
#  SConscript file for the common module library
######################################################
import os

Import('*')

######################################################
#  Retrieve list of files that need to be compiled
######################################################
srcs = ['IntrTypeM.f90']

############################################
#  Customize the construction environment  #
############################################

env = Environment(options = opts, tools=['fortran', 'f90', 'default'])
env.Append(ENV = {'PATH' : os.environ['PATH']})
dir = env.Dir(common_build_dir)
env['FORTRANMODDIR'] = dir
env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
env.Append(F90FLAGS = fortranFlags)


######################################################
#  Build the library
######################################################
common_lib = env.SharedLibrary(target = "common", source = srcs)
env.Install(install_dir, common_lib)

Return("common_lib")
