#!/bin/python
""" SConscript for main TRACE source code"""

######################################################
#  SConscript file for main TRACE source code
######################################################
import os
Import('*')

######################################################
#  Retrieve list of files that need to be compiled
######################################################
srcs = ['trac_lib.f90']

############################################
#  Customize the construction environment  #
############################################

env['F90PATH'] = [common_build_dir]
dir = env.Dir(trace_build_dir)
env['FORTRANMODDIR'] = dir

rpath_var = common_build_dir+os.sep+'libcommon.so'

env.Append(F90COM = ' 2>&1 | tee ${SOURCES.base}.diag')
env.Append(F90FLAGS = fortranFlags)
if platform=='darwin':
  env['RPATHPREFIX']='-Wl,-rpath '

######################################################
#  Build the library
######################################################

trace = env.SharedLibrary(target = "trace", source = srcs,
                          LIBS = 'common',
                          #LIBPATH = common_build_dir,
                          RPATH= common_build_dir)

######################################################
#
Return("trace")
